name: docker4640
on:
  push:
    branches:
      - 'master'
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: checks dir
      run: ls
    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
    - name: Push to Docker hub
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: jovan9876/acit4640app:latest
